global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-data-lake-foundation-47lining
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-data-lake-foundation-47liningt1:
    parameter_input: quickstart-data-lake-foundation-47lining-example-params1.json
    template_file: quickstart-data-lake-foundation-47lining-example1.template
  quickstart-data-lake-foundation-47liningt2:
    parameter_input: quickstart-data-lake-foundation-47lining-example-params2.json
    template_file: quickstart-data-lake-foundation-47lining-example2.template
