global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-data-lake-foundation-47lining
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  defaults:
    parameter_input: data-lake-defaults.json
    template_file: data-lake-foundation-master.template