global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-aws-datalake-foundation
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  multi-node-foundation:
    parameter_input: data-lake-foundation-multi-node.json
    template_file: data-lake-foundation-master.template
    regions:
      - us-east-1
  single-node-demonstration:
    parameter_input: data-lake-demonstration-single-node.json
    template_file: data-lake-demonstration-master.template
    regions:
      - us-west-2
